version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      npm: 7.5.2
  build:
    commands:
      - npm install
      - npm run build
artifacts:
    files:
      - index.html
      - dist/**/*
