version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo npm install -g npm@7.0.0
      - npm install
  build:
    commands:
      - npm run build
artifacts:
    files:
      - index.html
      - dist/**/*
