version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update
      - sudo apt-get install -y nodejs npm
      - npm install
  build:
    commands:
      - echo "Building application..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading artifacts..."
      
artifacts:
  files:
    - '**/*'
